---
ID: "6e691d31-01ba-4730-bcae-d7bd58b96c9a"
Parent: "199c0c47-25bc-4d2b-8829-5304c5395d06"
Template: "fd2059fd-6043-4dfe-8c04-e2437ce87634"
Path: "/sitecore/templates/Branches/Project/click-click-launch/Alaris/Add Partial Designs/Global/ProductContent"
SharedFields:
- ID: "55faae90-3bba-4f7f-96fe-13c3f40055ff"
  Hint: Signature
  Value: productcontent
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "6148bc13-bd97-44d4-9e56-b26f8f397767"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{974D5718-C25D-4FDA-90D4-F3E9829ECC90}"
              p:before="*"
              s:id="{C78595D2-0892-4EC6-9FF8-B71EDBF17861}"
              s:par="GridParameters=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D&amp;FieldNames&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=1"
              s:ph="headless-main" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260601T000000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6320b40e-eb7b-427b-a9f7-bb74ed0bf08d"
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260601T000000Z
